### ISSUE TITLE
Waiting for Wire.available() is not correct.

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit-VCNL40X0-PCB#3]
This line is often used : "while(!Wire.available());" but that is not correct.
After Wire.requestFrom(), the I2C transmission has completely finished, and Wire.available() returns the number of bytes in the buffer.

**Comment by ladyada** [comment]
this is the PCB repository

**Comment by Koepel** [comment]
I would like to re-open this issue. There is a Arduino file "vcnl4000.ino" with the mentioned issue in this PCB repository.

**Comment by Koepel** [comment]
I see it was fixed at 12 Aug 2017. Thank you.
